apiVersion: v1
kind: Secret
metadata:
  name: telegram-secrets
type: Opaque
data:
  TELEGRAM_TOKEN: ODE5NjkwNjY3MDpBQUVKNG0wU2xCYjNNckQycURyT2tMek1YYngzM19mdkhWYw==
  TELEGRAM_CHAT_ID: NjkwMTI1MjcxMA==